[versions]
agp = "8.10.1"
gsonVersion = "2.13.1"
hilt = "2.56.2"
espressoCoreVersion = "3.6.1"
junitJupiter = "5.8.1"
kotlin = "2.0.0"
coreKtx = "1.16.0"
junit = "4.13.2"
appcompat = "1.7.0"
ktorNetwork = "3.1.3"
material = "1.12.0"
activity = "1.10.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.9.0"
navigationFragmentKtx = "2.9.0"
navigationUiKtx = "2.9.0"
preferenceKtx = "1.2.1"
fragmentKtx = "1.8.7"
roomCompiler = "2.7.1"
window = "1.4.0"
room = "2.7.1"
ksp = "2.0.0-1.0.22"
junitKtx = "1.2.1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomCompiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomCompiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomCompiler" }
androidx-window = { module = "androidx.window:window", version.ref = "window" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gsonVersion" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
ktor-network = { module = "io.ktor:ktor-network", version.ref = "ktorNetwork" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationUiKtx" }
androidx-preference-ktx = { group = "androidx.preference", name = "preference-ktx", version.ref = "preferenceKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
androidx-room = { id = "androidx.room", version.ref="room" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }